name: lingualloop
description: "lingualloopmobile"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  # Geri döndük
  flutter_secure_storage: ^9.2.2
  dio: ^4.0.0
  json_annotation: ^4.8.0  # Bu da çalışıyor
  provider: ^6.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.5.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Roboto-Black.ttf
  assets:
    - assets/icons/home.png
    - assets/icons/profile.png
    - assets/icons/score.png
    - assets/icons/cup.png
    - assets/icons/fire.png
    - assets/icons/profilephoto.png
    - assets/icons/ticket.png
    - assets/icons/diamond.png
    - assets/icons/subtitleopen.png
    - assets/icons/subtitleclose.png
    - assets/icons/bookmark.png
    - assets/icons/ticket-one.png
    - assets/images/otta.png
    - assets/images/karty.png
    - assets/images/catsbattle.png
    - assets/gifs/diamond1.gif
