name: lingualloop
description: "lingualloopmobile"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  confetti: ^0.7.0
  flutter:
    sdk: flutter
  http: ^1.2.2  # Geri döndük
  flutter_secure_storage: ^9.2.2
  dio: ^4.0.0
  json_annotation: ^4.8.0  # Bu da çalışıyor
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.0.0
  path_provider: ^2.0.0
  image_picker: ^1.0.5

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.5.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Roboto-Black.ttf
  assets:
    - assets/icons/home.png
    - assets/icons/profile.png
    - assets/icons/score.png
    - assets/icons/cup.png
    - assets/icons/fire.png
    - assets/icons/profilephoto.png
    - assets/icons/ticket.png
    - assets/icons/diamond.png
    - assets/icons/settings.png
    - assets/icons/cancel.png
    - assets/icons/correct.png
    - assets/icons/pause.png
    - assets/icons/play.png
    - assets/icons/subtitleopen.png
    - assets/icons/subtitleclose.png
    - assets/icons/bookmark.png
    - assets/icons/info.png
    - assets/icons/next.png
    - assets/icons/ticket-one.png
    - assets/icons/leader.png
    - assets/icons/google-logo.png
    - assets/icons/apple-logo.png
    - assets/icons/logout.png

    - assets/images/otta.png
    - assets/images/otta_login.png
    - assets/images/karty.png
    - assets/images/catsbattle.png
    - assets/gifs/diamond1.gif

    - assets/badges/badge_1.png
    - assets/badges/badge_2.png
    - assets/badges/badge_3.png